### ISSUE TITLE
Integrate with Software Licensing's user-supplied license keys feature

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/EDD-Purchase-Limit#11]
Idea for enhancement. I've seen a number of customers selling items where they must supply license keys from an external system or party. When the supplied keys run out, SL starts auto generating them, but at least a few of these customers have wanted to prevent purchases until they can supply more licenses. A neat option might be to mark an item as sold out if the user-supplied keys are exhausted. Thoughts?

**Comment by pippinsplugins** [comment]
I've considered this before too. Might make more sense to be in Software Licensing though.

**Comment by ghost1227** [comment]
Agree that this is a cool idea, but it should be in SL.
