### ISSUE TITLE
Variable price default option not honored

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/EDD-Purchase-Limit#14]
When PL is active, the default choice in a variable price download no longer becomes selected. Instead the first item becomes selected in my tests.

**Comment by mintplugins** [comment]
Pull Request which fixes this:
https://github.com/easydigitaldownloads/EDD-Purchase-Limit/pull/22

**Comment by pippinsplugins** [comment]
@ghost1227 ?

**Comment by mintplugins** [comment]
Merged:
https://github.com/easydigitaldownloads/EDD-Purchase-Limit/pull/22
