### ISSUE TITLE
Item quantities are not subtracted for variable pricing options

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/EDD-Purchase-Limit#15]
Item quantities subtract from the stock amount just fine on single price downloads. But with variable pricing, purchasing a variation with and item quantity at checkout will only subtract 1 from the stock instead of the item quantity.

https://secure.helpscout.net/conversation/134251696/20014/

**Comment by SDavisMedia** [comment]
@ghost1227 Can you please look into this? I don't think it needs to wait for a full rewrite. I have another ticket on it today.

**Comment by akyusa01** [comment]
I have a ticket today with the same request.  https://secure.helpscout.net/conversation/172929534/28171/?folderId=180499

**Comment by pippinsplugins** [comment]
@ghost1227 Please look at this asap.

**Comment by brashrebel** [comment]
I got another ticket for this: https://secure.helpscout.net/conversation/225485615/37804/?folderId=180504

**Comment by pippinsplugins** [comment]
@ghost1227

**Comment by pippinsplugins** [comment]
@ghost1227 we had to refund a customer because of this today.

**Comment by SDavisMedia** [comment]
This appears to be working correctly for me. About to push the update live.
