### ISSUE TITLE
Use wp_get_current_user() instead of get currentuserinfo()

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/EDD-Purchase-Limit#18]
[This here function](https://github.com/easydigitaldownloads/EDD-Purchase-Limit/blob/master/includes/functions.php#L40) is on its way out. Should be using the [current equivalent](https://codex.wordpress.org/Function_Reference/wp_get_current_user).

**Comment by pippinsplugins** [comment]
@ghost1227 can you please merge this and get a new version prepared for me?
